/* commit.c generated by valac 0.14.2, the Vala compiler
 * generated from commit.vala, do not modify */

/* compile this file with `valac --pkg posix repo.vala -C -H repo.h`*/

#include <glib.h>
#include <glib-object.h>
#include <string.h>


#define SEAFILE_TYPE_COMMIT (seafile_commit_get_type ())
#define SEAFILE_COMMIT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SEAFILE_TYPE_COMMIT, SeafileCommit))
#define SEAFILE_COMMIT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SEAFILE_TYPE_COMMIT, SeafileCommitClass))
#define SEAFILE_IS_COMMIT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SEAFILE_TYPE_COMMIT))
#define SEAFILE_IS_COMMIT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SEAFILE_TYPE_COMMIT))
#define SEAFILE_COMMIT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SEAFILE_TYPE_COMMIT, SeafileCommitClass))

typedef struct _SeafileCommit SeafileCommit;
typedef struct _SeafileCommitClass SeafileCommitClass;
typedef struct _SeafileCommitPrivate SeafileCommitPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SeafileCommit {
	GObject parent_instance;
	SeafileCommitPrivate * priv;
	gchar _id[41];
	gchar* _creator;
	gchar* _desc;
	gint64 _ctime;
	gchar* _repo_id;
	gchar* _root_id;
};

struct _SeafileCommitClass {
	GObjectClass parent_class;
};

struct _SeafileCommitPrivate {
	gchar* _creator_name;
	gchar* _parent_id;
	gchar* _second_parent_id;
};


static gpointer seafile_commit_parent_class = NULL;

GType seafile_commit_get_type (void) G_GNUC_CONST;
#define SEAFILE_COMMIT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAFILE_TYPE_COMMIT, SeafileCommitPrivate))
enum  {
	SEAFILE_COMMIT_DUMMY_PROPERTY,
	SEAFILE_COMMIT_ID,
	SEAFILE_COMMIT_CREATOR_NAME,
	SEAFILE_COMMIT_CREATOR,
	SEAFILE_COMMIT_DESC,
	SEAFILE_COMMIT_CTIME,
	SEAFILE_COMMIT_PARENT_ID,
	SEAFILE_COMMIT_SECOND_PARENT_ID,
	SEAFILE_COMMIT_REPO_ID,
	SEAFILE_COMMIT_ROOT_ID
};
SeafileCommit* seafile_commit_new (void);
SeafileCommit* seafile_commit_construct (GType object_type);
const gchar* seafile_commit_get_id (SeafileCommit* self);
void seafile_commit_set_id (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_creator_name (SeafileCommit* self);
void seafile_commit_set_creator_name (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_creator (SeafileCommit* self);
void seafile_commit_set_creator (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_desc (SeafileCommit* self);
void seafile_commit_set_desc (SeafileCommit* self, const gchar* value);
gint64 seafile_commit_get_ctime (SeafileCommit* self);
void seafile_commit_set_ctime (SeafileCommit* self, gint64 value);
const gchar* seafile_commit_get_parent_id (SeafileCommit* self);
void seafile_commit_set_parent_id (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_second_parent_id (SeafileCommit* self);
void seafile_commit_set_second_parent_id (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_repo_id (SeafileCommit* self);
void seafile_commit_set_repo_id (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_root_id (SeafileCommit* self);
void seafile_commit_set_root_id (SeafileCommit* self, const gchar* value);
static void seafile_commit_finalize (GObject* obj);
static void _vala_seafile_commit_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seafile_commit_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


SeafileCommit* seafile_commit_construct (GType object_type) {
	SeafileCommit * self = NULL;
	self = (SeafileCommit*) g_object_new (object_type, NULL);
	return self;
}


SeafileCommit* seafile_commit_new (void) {
	return seafile_commit_construct (SEAFILE_TYPE_COMMIT);
}


const gchar* seafile_commit_get_id (SeafileCommit* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = (const gchar*) self->_id;
	return result;
}


void seafile_commit_set_id (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	memcpy (self->_id, _tmp0_, (gsize) 40);
	self->_id[40] = '\0';
	_tmp1_ = self->_id[40];
	g_object_notify ((GObject *) self, "id");
}


const gchar* seafile_commit_get_creator_name (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_creator_name;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_creator_name (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_creator_name);
	self->priv->_creator_name = _tmp1_;
	g_object_notify ((GObject *) self, "creator-name");
}


const gchar* seafile_commit_get_creator (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_creator;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_creator (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->_creator);
	self->_creator = _tmp1_;
	g_object_notify ((GObject *) self, "creator");
}


const gchar* seafile_commit_get_desc (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_desc;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_desc (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->_desc);
	self->_desc = _tmp1_;
	g_object_notify ((GObject *) self, "desc");
}


gint64 seafile_commit_get_ctime (SeafileCommit* self) {
	gint64 result;
	gint64 _tmp0_;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->_ctime;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_ctime (SeafileCommit* self, gint64 value) {
	gint64 _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->_ctime = _tmp0_;
	g_object_notify ((GObject *) self, "ctime");
}


const gchar* seafile_commit_get_parent_id (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_parent_id;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_parent_id (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_parent_id);
	self->priv->_parent_id = _tmp1_;
	g_object_notify ((GObject *) self, "parent-id");
}


const gchar* seafile_commit_get_second_parent_id (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_second_parent_id;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_second_parent_id (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_second_parent_id);
	self->priv->_second_parent_id = _tmp1_;
	g_object_notify ((GObject *) self, "second-parent-id");
}


const gchar* seafile_commit_get_repo_id (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_repo_id;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_repo_id (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->_repo_id);
	self->_repo_id = _tmp1_;
	g_object_notify ((GObject *) self, "repo-id");
}


const gchar* seafile_commit_get_root_id (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_root_id;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_root_id (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->_root_id);
	self->_root_id = _tmp1_;
	g_object_notify ((GObject *) self, "root-id");
}


static void seafile_commit_class_init (SeafileCommitClass * klass) {
	seafile_commit_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SeafileCommitPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_seafile_commit_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_seafile_commit_set_property;
	G_OBJECT_CLASS (klass)->finalize = seafile_commit_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_ID, g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_CREATOR_NAME, g_param_spec_string ("creator-name", "creator-name", "creator-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_CREATOR, g_param_spec_string ("creator", "creator", "creator", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_DESC, g_param_spec_string ("desc", "desc", "desc", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_CTIME, g_param_spec_int64 ("ctime", "ctime", "ctime", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_PARENT_ID, g_param_spec_string ("parent-id", "parent-id", "parent-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_SECOND_PARENT_ID, g_param_spec_string ("second-parent-id", "second-parent-id", "second-parent-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_REPO_ID, g_param_spec_string ("repo-id", "repo-id", "repo-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_ROOT_ID, g_param_spec_string ("root-id", "root-id", "root-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void seafile_commit_instance_init (SeafileCommit * self) {
	self->priv = SEAFILE_COMMIT_GET_PRIVATE (self);
}


static void seafile_commit_finalize (GObject* obj) {
	SeafileCommit * self;
	self = SEAFILE_COMMIT (obj);
	_g_free0 (self->priv->_creator_name);
	_g_free0 (self->_creator);
	_g_free0 (self->_desc);
	_g_free0 (self->priv->_parent_id);
	_g_free0 (self->priv->_second_parent_id);
	_g_free0 (self->_repo_id);
	_g_free0 (self->_root_id);
	G_OBJECT_CLASS (seafile_commit_parent_class)->finalize (obj);
}


GType seafile_commit_get_type (void) {
	static volatile gsize seafile_commit_type_id__volatile = 0;
	if (g_once_init_enter (&seafile_commit_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeafileCommitClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seafile_commit_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeafileCommit), 0, (GInstanceInitFunc) seafile_commit_instance_init, NULL };
		GType seafile_commit_type_id;
		seafile_commit_type_id = g_type_register_static (G_TYPE_OBJECT, "SeafileCommit", &g_define_type_info, 0);
		g_once_init_leave (&seafile_commit_type_id__volatile, seafile_commit_type_id);
	}
	return seafile_commit_type_id__volatile;
}


static void _vala_seafile_commit_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeafileCommit * self;
	self = SEAFILE_COMMIT (object);
	switch (property_id) {
		case SEAFILE_COMMIT_ID:
		g_value_set_string (value, seafile_commit_get_id (self));
		break;
		case SEAFILE_COMMIT_CREATOR_NAME:
		g_value_set_string (value, seafile_commit_get_creator_name (self));
		break;
		case SEAFILE_COMMIT_CREATOR:
		g_value_set_string (value, seafile_commit_get_creator (self));
		break;
		case SEAFILE_COMMIT_DESC:
		g_value_set_string (value, seafile_commit_get_desc (self));
		break;
		case SEAFILE_COMMIT_CTIME:
		g_value_set_int64 (value, seafile_commit_get_ctime (self));
		break;
		case SEAFILE_COMMIT_PARENT_ID:
		g_value_set_string (value, seafile_commit_get_parent_id (self));
		break;
		case SEAFILE_COMMIT_SECOND_PARENT_ID:
		g_value_set_string (value, seafile_commit_get_second_parent_id (self));
		break;
		case SEAFILE_COMMIT_REPO_ID:
		g_value_set_string (value, seafile_commit_get_repo_id (self));
		break;
		case SEAFILE_COMMIT_ROOT_ID:
		g_value_set_string (value, seafile_commit_get_root_id (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_seafile_commit_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeafileCommit * self;
	self = SEAFILE_COMMIT (object);
	switch (property_id) {
		case SEAFILE_COMMIT_ID:
		seafile_commit_set_id (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_CREATOR_NAME:
		seafile_commit_set_creator_name (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_CREATOR:
		seafile_commit_set_creator (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_DESC:
		seafile_commit_set_desc (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_CTIME:
		seafile_commit_set_ctime (self, g_value_get_int64 (value));
		break;
		case SEAFILE_COMMIT_PARENT_ID:
		seafile_commit_set_parent_id (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_SECOND_PARENT_ID:
		seafile_commit_set_second_parent_id (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_REPO_ID:
		seafile_commit_set_repo_id (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_ROOT_ID:
		seafile_commit_set_root_id (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



